### ISSUE TITLE
Jellyfin 播放弹幕时，中文显示为方框

### ISSUE THREAD

**Issue by xfrqh** [amtoaer/bili-sync#183]
## 问题
![2024-09-29_23-12-42](https://github.com/user-attachments/assets/98156c26-46f0-45b5-9519-45d561caeb9a)

尝试"直接播放"（不经转码）视频，弹幕中的中文显示为方框。
如果由服务器烧录字幕，则可以正常显示。

有没有大佬知道如何解决这个问题？

## 环境
我映射了包含很多字体的文件夹到Jellyfin的字体目录。播放番剧时，字幕可以正常显示，无论是直接播放还是转码播放。字体是VCB发布的超级字体整合包。

Jellyfin: `10.9.11`

> Jellyfin 的 Docker Compose：
```yaml
name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin

    volumes:
      - /app/jellyfin/config:/config
      - /app/jellyfin/cache:/cache

      - font:/usr/share/fonts/truetype/dejavu # 使用自己的字体替换系统字体
      # font_dir=/app/jellyfin/font && mkdir -p $font_dir && wget -P $font_dir https://github.com/wordshub/free-font/raw/master/assets/font/%E4%B8%AD%E6%96%87/%E6%96%B9%E6%AD%A3%E5%AD%97%E4%BD%93%E7%B3%BB%E5%88%97/%E6%96%B9%E6%AD%A3%E9%BB%91%E4%BD%93%E7%AE%80%E4%BD%93.ttf # 方正黑体

      - type: volume
        source: mynfs
        target: /mnt/nfs
        volume:
          nocopy: true

    network_mode: host
    restart: always


volumes:
  mynfs:
    external: true

  font:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.5.25,vers=4,nolock,soft,ro"
      device: ":/mnt/pool_1/Main/Service/Web_Assets/Font/超级字体整合包/精简包"
```
