### ISSUE TITLE
最新版无法启动，一直是重启中。

### ISSUE THREAD

**Issue by xushier** [amtoaer/bili-sync#279]
版本：2.4.0

运行方式：docker-compose

```yaml
version: "3.8"
services:
  bili-sync-rs:
    image: amtoaer/bili-sync-rs:v2.4.0
    container_name: BiliSync
    restart: unless-stopped
    user: 0:0
    tty: true
    ports:
      - 12345:12345
    networks:
      - unet
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - /mnt/cache/appdata/BiliSync:/app/.config/bili-sync:rw
      - /mnt:/mnt:rw
    labels:
      - traefik.enable=true
      - dnp=bili
      - net.unraid.docker.webui=${webui}
      - net.unraid.docker.icon=${icon}
    logging:
      driver: local
networks:
  unet:
    driver: bridge
    external: true
    attachable: true
```

配置文件：
```toml
auth_token = "马赛克"
bind_address = "0.0.0.0:12345"
video_name = "{{upper_mid}} - {{upper_name}}/{{pubtime}} - {{truncate title 230}} - {{bvid}}"
page_name = "{{pubtime}} - {{truncate ptitle 230}} - {{pid}}"
interval = 36000
upper_path = "/mnt/cache/metadata/Emby-Amilys/Metadata/metadata/people/"
nfo_time_type = "pubtime"
time_format = "%Y-%m-%d"

[credential]
sessdata = "马赛克"
bili_jct = "马赛克"
buvid3 = "马赛克"
dedeuserid = "马赛克"
ac_time_value = "马赛克"

[filter_option]
video_max_quality = "Quality8k"
video_min_quality = "Quality360p"
audio_max_quality = "QualityHiRES"
audio_min_quality = "Quality64k"
codecs = [
    "AV1",
    "HEV",
    "AVC",
]
no_dolby_video = false
no_dolby_audio = false
no_hdr = false
no_hires = false

[danmaku_option]
duration = 8.0
font = "微软雅黑"
font_size = 15
width_ratio = 1.2
horizontal_gap = 20.0
lane_size = 26
float_percentage = 0.5
bottom_percentage = 0.3
opacity = 75
bold = true
outline = 0.8
time_offset = 0.0

[favorite_list]

[collection_list]

[submission_list]
马赛克 = "/mnt/cachedl/General/Bilibili/"

[watch_later]
enabled = false
path = ""

[concurrent_limit]
video = 3
page = 2

[concurrent_limit.rate_limit]
limit = 3
duration = 250

```

日志输出：
```bash
BiliSync  | Feb 21 10:57:18  INFO 配置文件加载完毕，覆盖刷新原有配置
BiliSync  | Feb 21 10:57:18  INFO 检查配置文件..
BiliSync  | Feb 21 10:57:18 ERROR 没有配置任何需要扫描的内容，程序空转没有意义
BiliSync  | thread 'main' panicked at crates/bili_sync/src/config/mod.rs:164:13:
BiliSync  | 位于 /app/.config/bili-sync/config.toml 的配置文件不合法，请参考提示信息修复后继续运行
BiliSync  | stack backtrace:
BiliSync  |    0:     0x14fa6a109c3a - <unknown>
BiliSync  |    1:     0x14fa69c8e2b3 - <unknown>
BiliSync  |    2:     0x14fa6a105fb3 - <unknown>
BiliSync  |    3:     0x14fa6a109a92 - <unknown>
BiliSync  |    4:     0x14fa6a10aaa7 - <unknown>
BiliSync  |    5:     0x14fa6a10a90d - <unknown>
BiliSync  |    6:     0x14fa6a10b057 - <unknown>
BiliSync  |    7:     0x14fa6a10aefa - <unknown>
BiliSync  |    8:     0x14fa6a10a0e9 - <unknown>
BiliSync  |    9:     0x14fa6a10ab9c - <unknown>
BiliSync  |   10:     0x14fa698fb600 - <unknown>
BiliSync  |   11:     0x14fa69ba0814 - <unknown>
BiliSync  |   12:     0x14fa69b67bd6 - <unknown>
BiliSync  |   13:     0x14fa69dba8cf - <unknown>
BiliSync  |   14:     0x14fa698fac5c - <unknown>
BiliSync  |   15:     0x14fa69c1ee16 - <unknown>
BiliSync  |   16:     0x14fa69c1b6f5 - <unknown>
BiliSync  |   17:     0x14fa69a16ea3 - <unknown>
BiliSync  |   18:     0x14fa69a16d59 - <unknown>
BiliSync  |   19:     0x14fa6a0fdf1d - <unknown>
BiliSync  |   20:     0x14fa69c23f35 - <unknown>
```

配置目录和下载目录的权限配置都是root
