### ISSUE TITLE
出现这个问题是什么原因？所有视频下载失败，提示“出现常见错误，已忽略”“已成功，跳过”，打开文件夹一片空白，什么都下载不下来

### ISSUE THREAD

**Issue by calledsapy** [amtoaer/bili-sync#295]
出现这个问题是什么原因？所有视频下载失败，提示“出现常见错误，已忽略”“已成功，跳过”，打开文件夹一片空白，什么都下载不下来？![Image](https://github.com/user-attachments/assets/4ed24407-7381-40a2-b5da-2f24b66074ed)

**Comment by calledsapy** [comment]
新手小白求教，我设置了环境变量也还是不行，![Image](https://github.com/user-attachments/assets/f3489d18-7a13-4ab1-86d1-473e56a92834)

**Comment by calledsapy** [comment]
fnos，配置文件路径这样写对么？![Image](https://github.com/user-attachments/assets/e24ea9bc-23d7-481b-a1dd-026890cfe35d)

**Comment by cxw620** [comment]
(插一嘴主题无关的事儿: playurl 里面有 mid 的, 建议码一下)

**Comment by Megestus** [comment]
我也是个小白，我的 compose 是这样的看看，能不能帮到你,正如作者提到的备注你先执行一下 id ${user} 获取一下uid 和 gid ，这个可以通过putty链接终端查一下，或者其他的终端应用链接。

```
services:
  bili-sync-rs:
    # 不推荐使用 latest 这种模糊的 tag，最好直接指明版本号
    image: amtoaer/bili-sync-rs:latest
    restart: unless-stopped
    network_mode: bridge
    # 该选项请仅在日志终端支持彩色输出时启用，否则日志中可能会出现乱码
    tty: true
    # 非必需设置项，推荐设置为宿主机用户的 uid 及 gid (`$uid:$gid`)
    # 可以执行 `id ${user}` 获取 `user` 用户的 uid 及 gid
    # 程序下载的所有文件权限将与此处的用户保持一致，不设置默认为 Root
    user: 0:0
    hostname: bili-sync-rs
    container_name: bili-sync-rs
    # 程序默认绑定 0.0.0.0:12345 运行 http 服务
    # 可同时修改 compose 文件与 config.toml 变更服务运行的端口
    ports:
      - 12345:12345
    volumes:
    - /volume1/docker/bili_sync/config:/app/.config/bili-sync
    - /volume1/bili_video:/videos
    # 如果你使用的是群晖系统，请移除最后的 logging 配置，否则会导致日志不显示
    logging:
        driver: "local"

```
